 use MandiriUtamaFinanceTest;
 go

 -- Soal 5a
 SELECT 
	e.EMPL_NAME,
	e.EMPL_JOB_ID,
	FORMAT (e.EMPL_SALARY, 'c', 'id-ID') AS EMPL_SALARY,
	j.EMPL_JOB_DESC
 FROM EMPL AS e
 	INNER JOIN JOB AS j ON j.EMPL_JOB_ID = e.EMPL_JOB_ID
 ORDER BY e.EMPL_NAME

 -- Soal 5b
 SELECT 
 	EMPL_NAME,
	EMPL_JOB_ID,
	EMPL_SALARY
 FROM (SELECT
			EMPL_NAME,
			EMPL_JOB_ID,
			FORMAT (EMPL_SALARY, 'c', 'en-US') AS EMPL_SALARY,
 			DENSE_RANK() OVER(PARTITION BY EMPL_JOB_ID ORDER BY EMPL_SALARY DESC) AS SalaryRank
 		FROM EMPL) AS RankedData
 WHERE SalaryRank = 1
 ORDER BY EMPL_SALARY;

 -- Soal 1
 SELECT
	c1.KODE_CABANG,
	c1.NAMA_CABANG,
	c1.KODE_AREA,
	c2.NAMA_CABANG AS NAMA_AREA
 FROM MASTER_CABANG AS c1
	INNER JOIN MASTER_CABANG AS c2 ON c1.KODE_AREA = c2.KODE_CABANG
 WHERE c1.TIPE_CABANG ='CABANG'

 -- Soal 2
 SELECT 
	n.KODE_NASABAH,
	n.NAMA_NASABAH,
	c1.KODE_CABANG,
	c1.NAMA_CABANG,
	c2.NAMA_CABANG AS NAMA_AREA
 FROM MASTER_CUST AS n
	JOIN MASTER_CABANG AS c1 ON n.KODE_CABANG = c1.KODE_CABANG
	JOIN MASTER_CABANG AS c2 ON c1.KODE_AREA = c2.KODE_CABANG

 -- Soal 3
 SELECT 
	t.KODE_CABANG,
	c.NAMA_CABANG as CABANG,
	t.KODE_NASABAH,
	n.NAMA_NASABAH,
	FORMAT (t.HARGA_UNIT, 'c', 'id-ID') AS HARGA_UNIT,
	FORMAT(t.TANGGAL_TRANSAKSI,'dd-MMM-yy h:mm:ss tt')
 FROM TRANS_CUST AS t
 JOIN MASTER_CUST AS n ON t.KODE_NASABAH = n.KODE_NASABAH
 JOIN MASTER_CABANG AS c ON t.KODE_CABANG = c.KODE_CABANG

 -- Soal 4
 SELECT 
	t.KODE_CABANG,
	c.NAMA_CABANG,
	COUNT(t.KODE_CABANG) AS TOTAL_KONTRAK
 FROM TRANS_CUST AS t
 JOIN MASTER_CABANG AS c ON t.KODE_CABANG = c.KODE_CABANG
 GROUP BY t.KODE_CABANG, c.NAMA_CABANG

 -- Soal 5
 SELECT 
	MONTH(t.TANGGAL_TRANSAKSI) AS MONTH,
	YEAR(t.TANGGAL_TRANSAKSI) AS YEAR,
	COUNT(t.NOMOR_KONTRAK) AS TOTAL_KONTRAK
 FROM TRANS_CUST AS t
 WHERE YEAR(t.TANGGAL_TRANSAKSI) = '2015'
 GROUP BY MONTH(t.TANGGAL_TRANSAKSI),YEAR(t.TANGGAL_TRANSAKSI)

-- Soal 6
use MandiriUtamaFinanceTest;
go
CREATE OR ALTER PROCEDURE HighestOrderInAMonthByYear 
	@year int
AS
BEGIN
SELECT 
	PERIODE,NOMOR_KONTRAK,NAMA_NASABAH,HARGA_UNIT 
FROM(
	SELECT 
		FORMAT(t.TANGGAL_TRANSAKSI,'yyyyMM') AS PERIODE,
		t.NOMOR_KONTRAK,
		n.NAMA_NASABAH,
		FORMAT (t.HARGA_UNIT, 'c', 'id-ID') AS HARGA_UNIT,
		DENSE_RANK() OVER (PARTITION BY MONTH(t.TANGGAL_TRANSAKSI) ORDER BY t.HARGA_UNIT DESC) AS RANK
	FROM TRANS_CUST AS t
		JOIN MASTER_CUST AS n ON n.KODE_NASABAH = t.KODE_NASABAH
	WHERE YEAR(t.TANGGAL_TRANSAKSI) = @year) RANK_DATA 
	WHERE RANK = 1
END


EXEC HighestOrderInAMonthByYear @year = 2015;